### ISSUE TITLE
module, function and line are logged after msg body

### ISSUE THREAD

**Issue by linearregression** [heroku/lager_elogfmt_formatter#2]
PEr readME.
module, function and line will be shown automatically if configured correctly.
But the log below shows that module, funciton and line are ordered after message.

code that triggered logging lager:info("start/2").

log:
app=lager_test severity=info msg="Application lager started on node \'lager_test@127.0.0.1\'"
app=lager_test severity=info msg="Application lager_test started on node \'lager_test@127.0.0.1\'"
app=lager_test severity=info msg="started/2" node=lager_test@127.0.0.1 line=24 function=start module=lager_test_app application=lager_test
app=lager_test severity=info msg="Application lager started on node \'lager_test@127.0.0.1\'"
app=lager_test severity=info msg="Application lager_test started on node \'lager_test@127.0.0.1\'"

rebar.config: 

{deps, [
    {lager, ".*", {git, "git://github.com/basho/lager.git", {tag, "3.0.2"}}},
    {lager_elogfmt_formatter,
     {git, "https://github.com/heroku/lager_elogfmt_formatter.git", {tag, "1.0.0"}}}
]}.

sys.config:

```
{lager, [
    {log_root, "./log_me"},
    {error_logger_hwm, 8192},
    {colored, false},
    {crash_log, "crash.log"},
    {crash_log_size, 0},
    {crash_log_count, 14},
    {handlers, [
      {lager_console_backend, [info, {lager_default_formatter, [date,"#",time,"#",severity,"#",node,"#",pid,"#",module,"#",function,"#",file,"#",line,"#",message,"\r\n"]}]},
      {lager_file_backend, [
        {file, "service.log"}, {level, info}, {formatter, lager_elogfmt_formatter}, {size, 0}, {date, "$D0"}, {count, 7},
            {formatter_config, [{app, "lager_test"}, "[", date, " ", time, "] severityfbkend=", severity, " module=", module," function=", function, " "," pid=", pid, " ", message, "\n"]}
        ]}
    ]}
]}
```

].

**Comment by ypaq** [comment]
Apologies for the delayed response. The purpose of `logfmt` is to provide a structured log format that is computer _and_ human readable. This lager formatter is tailored for (but not limited to) logs going to Splunk following their [logging best practices](http://dev.splunk.com/view/logging-best-practices/SP-CAAADP6). You might find [this post](https://brandur.org/logfmt) informative as well. Especially, for  computer readable logs the order of key-value pairs is irrelevant. By design, `lager_elogfmt_formatter` ignores the part of the formatter config to set specifics for the actual formatting. 

If in your case the order matters, you might want give preference to the `lager_default_formatter` with a specific configuration on how to format your logs as you have done in your `sys.config` with  `lager_file_backend`. The `lager_default_formatter` provides means for conditional formatting to handle missing keys. 

That being said, I'm open to the idea of adjusting the order of keys if there's a good reason for it.
